const IMAGES = {
  viniferaLogo: "/image/viniferaLogo.svg",
  Adminloginbg: "/image/adminloginbg.jpg",
  corporateone: "/image/cp1.jpg",
  goa: "/image/goa.jpg",
  ayodhya: "/image/ayodhya.jpg",
  jodhpur: "/image/jodhpur.jpg",
  rajasthan: "/image/rajasthan.jpg",
  sectionfour: "/image/section-4.jpg",
  herolanding: "/image/herolanding.png",
  rajasthanhome: "/image/rajasthanhome.jpg",
  homepackage1: "/image/homepackage1.png",
  homepackage2: "/image/homepackage2.png",
  homepackage3: "/image/homepackage3.png",
  homepackage4: "/image/homepackage4.png",
  ticketslanding: "/image/ticketslanding.jpg",
  tickettravel: "/image/tickettravel.jpg",
  faq: "/image/faq.jpg",
  faqicon: "/image/faqicon.jpg",
  contact: "/image/contact.jpg",
  testimonialsbg: "/image/testimonialsbg.jpg",
  specialtours: "/image/special_tour.jpg",
  testimonialslanding: "/image/testimonialslanding.avif",
  GroupTours: "/image/group_tour.jpg",
  feedback: "/image/feedback.png",
  scrollone: "/image/scroll1.jpg",
  scrolltwo: "/image/scroll2.jpg",
  scrollthree: "/image/scroll3.jpg",
  scrollfour: "/image/scroll4.jpg",
  passport: "/image/Passport.png",
  profile: "/image/profile.jpeg",
  profile1: "/image/profile1.jpeg",
  profile2: "/image/profile2.jpeg",
  travel: "/image/travel.jpg",
  plane: "/image/plane.png",
  usa: "/image/usa.jpg",
  bali: "/image/bali.jpg",
  rome: "/image/rome.jpg",
  japan: "/image/japan.jpg",
  herocardone:"/image/herocard1.jpg",
  herocardtwo:"/image/herocard2.jpg",
  herocardthree:"/image/herocard3.jpg",
  herocardfour:"/image/herocard4.jpg",
  corparateExperience:"/image/corparateExperience.jpg",
  corporateGoa:"/image/corporateGoa.jpg",
  corporateGujarat:"/image/corporateGujarat.jpg",
  corporateKerla:"/image/corporateKerla.jpg",
  corporateSikkim:"/image/corporateSikkim.jpg",
  corporateRajesthan:"/image/corporateRajesthan.jpg",
  landingCatOne:"/image/landingCatOne.jpg",
  landingCatTwo:"/image/landingCatTwo.jpg",
  landingCatThree:"/image/landingCatThree.jpg",
  landingCatFour:"/image/landingCatFour.jpg",
  landingCatFive:"/image/landingCatFive.jpg",
  landingCatSix:"/image/landingCatSix.jpg",
  landingCatSeven:"/image/landingCatSeven.jpg",
  landingCatEight:"/image/landingCatEight.jpg",


};

export default IMAGES;
